###  Before running docker-compose.yml, set a new custom admin password using the following command: 
###  export OPENSEARCH_INITIAL_ADMIN_PASSWORD=<custom-admin-password>


services:
  # MongoDB
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    restart: always

  # OpenSearch
  opensearch:
    image: opensearchproject/opensearch:latest
    environment:
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - action.auto_create_index=false
      - plugins.security.ssl.http.enabled=false
      - plugins.security.disabled=true
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    restart: always

  # Graylog
  graylog:
    image: graylog/graylog:6.0.1
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=${GRAYLOG_ELASTICSEARCH_HOSTS}
      - GRAYLOG_PASSWORD_SECRET=$(pwgen -s 96 1)
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_NODE_ID_FILE=/usr/share/graylog/data/node-id
      - GRAYLOG_HTTP_ENABLE_TLS=true
      - GRAYLOG_HTTP_TLS_CERT_FILE=/etc/graylog/server/certs/graylog-certificate.pem
      - GRAYLOG_HTTP_TLS_KEY_FILE=/etc/graylog/server/certs/graylog-privatekey.pem
    entrypoint: /usr/bin/tini -- wait-for-it ${GRAYLOG_ELASTICSEARCH_HOSTS} --  /docker-entrypoint.sh
    ports:
      - "5044:5044/tcp"   # Beats
      - "5140:5140/tcp"   # Syslog TCP
      - "5140:5140/udp"   # Syslog UDP
      - "5555:5555/tcp"   # RAW TCP
      - "5555:5555/udp"   # RAW UDP
      - "9000:9000/tcp"   # Server API
      - "12201:12201/tcp" # GELF TCP
      - "12201:12201/udp" # GELF UDP
      - "13301:13301/tcp" # Forwarder data
      - "13302:13302/tcp" # Forwarder config
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/journal
      - ./ssl:/etc/graylog/server/certs
    depends_on:
      - mongodb
      - opensearch
    restart: always

volumes:
  mongodb_data:
  opensearch_data:
  graylog_data:
  graylog_journal:
